### ISSUE TITLE
update

### ISSUE THREAD

**Issue by wolfboy555** [SuperHackio/SMG2MarioConstEditor#2]
the program needs updating to the latest net version which is 8.0. 5.0 is very outdated now and i would like to use this program.

<img width="250" alt="Screenshot 2024-10-16 154459" src="https://github.com/user-attachments/assets/8601afdd-dc8c-48ac-9d68-a5cfe07904ec">

**Comment by SuperHackio** [comment]
Updated to .NET 8.0

**Comment by wolfboy555** [comment]
Thanks for updating the program
